<?php
    $url_first    = $this->queryUrl(array('page' => $this->first)); 
    $url_previous = $this->queryUrl(array('page' => $this->previous)); 
    $url_next     = $this->queryUrl(array('page' => $this->next)); 
    $url_last     = $this->queryUrl(array('page' => $this->last)); 
?>
<div class="pagination">

    <ul class="pages">

        <li class="previous">
            <?php if (isset($this->previous)): ?>
              <a href="<?= $url_previous ?>">previous</a>
            <?php else: ?>
              <span class="disabled">previous</span>
            <?php endif; ?>
        </li>

        <?php foreach ($this->pagesInRange as $page): ?>
            <li class="page">
              <?php if ($page != $this->current): ?>
                <a href="<?= $this->queryUrl(array('page' => $page)); ?>"><?= $page; ?></a>
              <?php else: ?>
                <span class="current"><?= $page; ?></span>
              <?php endif; ?>
            </li>
        <?php endforeach; ?>

        <li class="next">
            <?php if (isset($this->next)): ?>
              <a href="<?= $url_next ?>">next</a>
            <?php else: ?>
              <span class="disabled">next</span>
            <?php endif; ?>
        </li>
    </ul>

    <div class="page_position">
        <?= $this->firstItemNumber; ?> - 
        <?= $this->lastItemNumber; ?>
        of <?= $this->totalItemCount; ?>
    </div>

    <div class="page_size">
        show
        <ul class="page_size_choices">
            <?php
                $sizes = array(5, 10, 25, 50, 100, 200);
                $first = true;
                foreach ($sizes as $size) {
                    ?>
                        <?php if ($size == $this->itemCountPerPage): ?>
                            <li class="selected <?= ($first) ? 'first' : '' ?>">
                                <span><?= $size ?></span>
                            </li>
                        <?php else: ?>
                            <li class="<?= ($first) ? 'first' : '' ?>">
                                <a href="<?= $this->queryUrl(array('set_page_size' => $size)) ?>"><?= $size ?></a>
                            </li>
                        <?php endif ?>
                    <?php
                    $first = false;        
                } 
            ?>
        </ul>
        items per page
    </div>

</div>
