<?php
    $auth_post = ($this->auth_profile && 
        $this->post['profile_id'] == $this->auth_profile['id']);

    $profile_home_url = $this->url(
        array('screen_name' => $this->post['screen_name']), 
        'post_profile'
    );
?>
<li class="post" id="post-<?= $this->post['hash'] ?>">
    <h4 class="title">
        <a href="<?= $this->escape($this->post['url']) ?>"><?= $this->escape($this->post['title']) ?></a>
    </h4>
    <?php if (!empty($this->post['notes'])): ?>
        <p class="notes"><?= $this->escape($this->post['notes']) ?></p>
    <?php endif ?>
    <div class="meta">
        <ul class="tags">
            <?php foreach ($this->post['tags_parsed'] as $tag): ?>
                <li class="tag"><a href="<?= $profile_home_url . '/' . $this->escape(rawurlencode($tag)) ?>"><?= $this->escape($tag) ?></a></li>
            <?php endforeach; ?>
        </ul>
        <span class="author"><a href="<?= $profile_home_url ?>"><?= $this->escape($this->post['screen_name']) ?></a></span>
        <span class="date"><a class="view" href="<?= $this->url(array('uuid'=>$this->post['uuid']), 'post_view') ?>"><?= $this->escape($this->post['user_date']) ?></a></span>
        <ul class="commands">
            <?php if ($auth_post): ?>
                <li class="first"><a class="edit" href="<?= $this->url(array('uuid'=>$this->post['uuid']), 'post_save_edit') ?>">edit</a></li>
                <li><a class="delete" href="<?= $this->url(array('uuid'=>$this->post['uuid']), 'post_delete') ?>">delete</a></li>
            <?php else: ?>
                <li class="first"><a class="copy" href="<?= $this->url(array('uuid'=>$this->post['uuid']), 'post_save_copy') ?>">copy</a></li>
            <?php endif ?>
        </ul>
    </div>

    <?php if (false): ?>
        <pre><?= var_export($this->post->toArray()) ?></pre>
    <?php endif ?>

</li>
