<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head>  
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
        <title>memex</title>
    </head> 
    <body>
        <?= $this->layout()->content ?>
        <?php
            $md_content = $this->placeholder('markdown');
            if ($md_content) {
                require_once 'Markdown.php';
                echo Markdown($md_content);
            }
        ?>
    </body>
</html>
