<?php $this->placeholder('crumbs')->captureStart() ?>
    / <a href="<?= $this->url(array(), 'profile_settings') ?>">settings</a>
<?php $this->placeholder('crumbs')->captureEnd() ?>

<?php $this->placeholder('doc_content')->captureStart() ?>

## Profile

* [Edit profile details][ed_prof] 
    * change screen name, bio, etc.
* [Change login password][ch_pass] 
    * change current login password
* [Manage profile logins][manage_logins] 
    * create and remove logins for this profile
* [Delete profile][delete_prof] 
    * delete this profile altogether

[ed_prof]: <?= $this->url(array(), 'profile_settings') ?> "Edit profile"
[delete_prof]: <?= $this->url(array(), 'profile_settings') ?> "Delete profile"
[ch_pass]: <?= $this->url(array(), 'profile_settings') ?> "Change password"
[manage_logins]: <?= $this->url(array(), 'profile_settings') ?> "Change password"

## Services

* [delicious.com item import][delicious]
    * import items from a delicious.com account
* [delicious.com activity replication][delicious]
    * copy item updates and deletions to a delicious.com account

[delicious]: <?= $this->url(array(), 'profile_settings_delicious') ?> "delicious.com account integration"

<?php $this->placeholder('doc_content')->captureEnd() ?>
