<?php $this->placeholder('crumbs')->captureStart() ?>
    <?php if (empty($this->tags)): ?>
    / <a href="<?= $this->url() ?>">recent</a>
    <?php else: ?>
        / tag / <a href="<?= $this->url() ?>"><?= join(' + ', $this->tags) ?></a>
    <?php endif ?>
<?php $this->placeholder('crumbs')->captureEnd() ?>

<?php $this->placeholder('infobar')->captureStart() ?>
    <?php if (empty($this->tags)): ?>
        Recent items (<?= $this->posts_count ?>)
    <?php else: ?>
        Recent items tagged <?php foreach ($this->tags as $tag): ?>
            <a href="<?= $this->url(array('tags' => $tag), 'post_tag') ?>"><?= $this->escape($tag) ?></a>
        <?php endforeach ?> (<?= $this->posts_count ?>)
    <?php endif ?>
<?php $this->placeholder('infobar')->captureEnd() ?>

<?php if (empty($this->posts)): ?>

    <div class="message">
        <?php if (!$this->auth_profile || $this->screen_name != $this->auth_profile['screen_name']): ?>
            <h2>No items found.</h2>
        <?php else: ?>
            <?php if (!$this->tags): ?>
                <h2>You have no bookmarks, yet.</h2>
                <p>
                    Why not start by <a href="<?= $this->url(array(), 'post_save') ?>">saving a new bookmark</a>?
                </p>
            <?php else: ?>
                <h2>You have no bookmarks tagged <?php foreach ($this->tags as $tag): ?><?= $this->escape($tag) ?><?php endforeach ?>.</h2>
            <?php endif ?>
        <?php endif ?>
    </div>

<?php else: ?>

    <?= $this->paginationControl(
        $this->paginator, 'Sliding', 'pagination_mini_control.phtml'
    ); ?>

    <ul class="posts">
        <?php foreach ($this->posts as $post): ?>
            <?= $this->partial('post.phtml', array(
                'profile'      => $this->profile,
                'auth_profile' => $this->auth_profile,
                'post'         => $post
            )); ?>
        <?php endforeach; ?>
    </ul>

    <?= $this->paginationControl(
        $this->paginator, 'Sliding', 'pagination_control.phtml'
    ); ?>

<?php endif ?>
