<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<?php
    $request         = Zend_Controller_Front::getInstance()->getRequest();
    $action_name     = $request->getActionName();
    $controller_name = $request->getControllerName();

    if (null === $this->auth_profile) {
    } else {
        $profile_home_url = $this->url(
            array('screen_name' => $this->auth_profile['screen_name']), 
            'post_profile'
        );
    }

    $sidebar_content = $this->placeholder('sidebar');
?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head>  
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
        <title>memex</title>
        <link href="<?= $this->baseUrl('/css/nostalgia/main.css') ?>" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?= $this->baseUrl('/css/nostalgia/ctrl_' . $controller_name . '.css') ?>" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?= $this->baseUrl('/css/nostalgia/ctrl_' . $controller_name . '_act_' . $action_name . '.css') ?>" media="screen" rel="stylesheet" type="text/css" />
    </head> 
    <body id="<?= 'ctrl_' . $controller_name . '_act_' . $action_name ?>" 
            class="<?= 'ctrl_' . $controller_name ?> <?= 'act_' . $action_name ?> <?= 'ctrl_' . $controller_name . '_act_' . $action_name ?>">
        <div id="page" class="<?= ($sidebar_content != '') ? 'with_sidebar' : '' ?>">

            <div id="header">

                <div class="logo"><span></span></div>

                <div class="crumbs">
                    <span class="title"><a href="/">memex</a></span>
                    <?= $this->placeholder('crumbs') ?>
                </div>

                <div class="main">
                    <?php if (null != $this->auth_profile): ?>
                        <ul class="nav">
                            <li class="first"><a href="<?= $profile_home_url ?>">your bookmarks</a></li> 
                            <li><a href="<?= $this->url(array(), 'post_save', true) ?>">save new</a></li>
                        </ul>
                    <?php endif ?>
                </div>

                <div class="sub">

                    <div class="auth">
                        <ul class="nav">
                            <?php if (null === $this->auth_profile): ?>
                                <li class="first"><a href="<?= $this->url(array(), 'auth_login', true) ?>">login</a></li>
                                <li><a href="<?= $this->url(array(), 'auth_register', true) ?>">register</a></li>
                            <?php else: ?>
                                <li class="first">logged in as <a href="<?= $profile_home_url ?>"><?= $this->escape($this->auth_profile['screen_name']) ?></a></li>
                                <li><a href="<?= $this->url(array(), 'auth_logout', true) ?>">logout</a></li>
                            <?php endif; ?>
                        </ul>
                    </div>

                </div>

            </div>

            <div id="infobar">
                <?= $this->placeholder('infobar') ?>
            </div>

            <div id="middle">
                <div id="content">
                    <?= $this->layout()->content ?>
                </div>
                <?php if ($sidebar_content): ?>
                    <div id="sidebar">
                        <?= $sidebar_content ?>
                    </div>
                <?php endif ?>
            </div>

            <div id="footer">
                <ul class="nav">
                    <li class="first"><a href="<?= $this->url(array(), 'post_tag_recent') ?>">memex</a></li>
                    <li><a href="<?= $this->url(array('path'=>'README'), 'doc_index') ?>">about</a></li>
                    <li><a href="<?= $this->url(array('path'=>'TODO'), 'doc_index') ?>">todo</a></li>
                    <?= $this->placeholder('footer_nav') ?>
                </ul>

                <a class="license" rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/" title="This work is licensed under a Creative Commons Attribution-Share Alike 3.0 Unported License"><img alt="Creative Commons License" src="http://i.creativecommons.org/l/by-sa/3.0/80x15.png" /></a>

            </div>

        </div>

        <script src="<?= $this->baseUrl('/js/nostalgia/main.js') ?>" type="text/javascript"></script>
        <script src="<?= $this->baseUrl('/js/nostalgia/ctrl_' . $controller_name . '.js') ?>" type="text/javascript"></script>
        <script src="<?= $this->baseUrl('/js/nostalgia/ctrl_' . $controller_name . '_act_' . $action_name . '.js') ?>" type="text/javascript"></script>
    </body>
</html>
